# Generated by Django 5.1.7 on 2025-04-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_myuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
