# Generated by Django 5.1.7 on 2025-04-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_myuser_latitude_myuser_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=5),
        ),
    ]
