# Generated by Django 5.1.7 on 2025-04-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_myuser_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='theme',
            field=models.CharField(default='light', max_length=5),
        ),
    ]
