# Generated by Django 5.1.7 on 2025-04-13 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_swipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Swipe',
        ),
    ]
