# Generated by Django 5.1.7 on 2025-06-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_myuser_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='team_name',
            field=models.CharField(default='Unknown Team', max_length=100),
        ),
    ]
