# Generated by Django 5.1.7 on 2025-06-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_myuser_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='team_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
