# Generated by Django 5.1.7 on 2025-04-13 21:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='swipe',
            old_name='from_user',
            new_name='user_from',
        ),
        migrations.RenameField(
            model_name='swipe',
            old_name='to_user',
            new_name='user_to',
        ),
        migrations.AlterUniqueTogether(
            name='swipe',
            unique_together={('user_from', 'user_to')},
        ),
    ]
