# Generated by Django 5.1.7 on 2025-04-28 20:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='room_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
